#!/usr/bin/python2

def Hello(anyone):                      #function with 1 parameter...
        var='Hello ' + anyone
        return var                      #returing 1 value...

def main():
	name='Pooja'                          #storing a value in a variable...
        text= Hello(name)               #storing a function in a variable...
        print(text)                     #printing that function...

if __name__=='__main__':
        main()
